from decoder import Decoder
from pyiiasmh.errors import UnsupportedOSError, CodetypeError
import configparser
from pathlib import Path

config = configparser.ConfigParser()
config.read(Path(__file__).parent / "settings.ini")

def resolve_path(path_str):
    path = Path(path_str)
    return path if path.is_absolute() else (Path(__file__).parent / path)

active_gecko = config.getboolean("Active File", "active_gecko")
active_asm = config.getboolean("Active File", "active_asm")
gecko_path = resolve_path(config["Custom Path"]["input_gecko_path"])
asm_path = resolve_path(config["Custom Path"]["input_asm_path"])
script_path = resolve_path(config["Custom Path"]["output_script_path"])
        
def write_python(bapo, values):
    bapo_int = int(bapo, 16)
    code_lines = [
        "# This script was generated by scripts/gecko_to_script/main.py.",
        "",
        "from dolphin import memory  # type: ignore",
        "",
        "def main():",
        f"    hook = 0x{bapo_int:X}",
        f"    instructions = {'[' + ', '.join(hex(int(v, 16)) for v in values.split()) + ']'}",
        "    for i, value in enumerate(instructions):",
        "        memory.write_u32(hook + i * 4, value)",
        f"    memory.invalidate_icache(hook, len(instructions) * 4)",
        "",
        "if __name__ == '__main__':",
        "    main()",
        ""
    ]

    with open(script_path, "w") as f:
        f.write("\n".join(code_lines))
        
        

def main(type: str, path: Path):
    try:
        decoder = Decoder()
        out = decoder.run(type, str(path))
        hex = out[0]
        bapo = out[1]
        codetype = out[4]
        print(f"Codetype: {codetype}\nHook address: {bapo}")
        print("\n-----------------\n" + hex.strip() + "\n-----------------\n")
        write_python(bapo, hex)
    except (UnsupportedOSError, CodetypeError) as e:
        print(f"\033[91m[ERROR]\n{e}\033[0m")

if active_gecko:
    main("gecko", gecko_path)
elif active_asm:
    main("asm", asm_path)
else:
    print("No active file selected")
