# This script was generated by scripts/gecko_to_script/main.py.

from dolphin import memory  # type: ignore

def main():
    hook = 0x807F7F88
    instructions = [0x60000000]
    for i, value in enumerate(instructions):
        memory.write_u32(hook + i * 4, value)
    memory.invalidate_icache(hook, len(instructions) * 4)

if __name__ == '__main__':
    main()
