import binascii
import re
import shutil
import sys
import tempfile
from argparse import ArgumentParser, Namespace
from pathlib import Path
from typing import Any, Optional, Tuple, Union

class Decoder():
    def __init__(self):
        super().__init__()
        self.opcodes = None
        self.geckocodes = None
        self.bapo = None
        self.codetype = None
        self.codetypes = ("04", "14", "05", "15", "06", "07", "16", "17", "C0", "C2", "C3", "D2", "D3", "F2", "F3", "F4", "F5")
        
    def write_python(self, code: Tuple[str, str, str, str, str], script_path) -> str:
        lines, bapo, xor, chksum, codetype = code
        if codetype == "C2D2":
            bapo_int = int(bapo, 16)
            code_lines = [
                "# This script was generated by scripts/gecko_to_script/main.py.",
                "",
                "from dolphin import memory  # type: ignore",
                "",
                "def main():",
                f"    hook = 0x{bapo_int:X}",
                f"    instructions = {'[' + ', '.join(hex(int(v, 16)) for v in lines.split()) + ']'}",
                "    for i, value in enumerate(instructions):",
                "        memory.write_u32(hook + i * 4, value)",
                f"    memory.invalidate_icache(hook, len(instructions) * 4)",
                "",
                "if __name__ == '__main__':",
                "    main()",
                ""
            ]

            with open(script_path, "w") as f:
                f.write("\n".join(code_lines))
        
    def split_types(self, code: str) -> list[str]:
        types = []
        for line in code.split("\n"):
            if line.strip():
                if line.startswith("0x"):
                    types.append(line.strip())
                else:
                    types[-1] += " " + line.strip()
        return types

    def deconstruct_code(self, codes: str, cFooter: bool = True) -> Tuple[str, str, str, str, str]:
        if codes[:2].upper() not in self.codetypes:
            raise ValueError(f"Invalid codetype {codes[:2]}.\nAllowed codetypes: {', '.join(self.codetypes)}")

        bapo = None
        xor = None
        chksum = None
        codetype = "C0"

        if codes[:2] != "C0":
            codetype = "C2D2"
            bapo = {"0": "8", "1": "0", "C": "8", "D": "0", "F": "8"}.get(codes[0], "8")
            if codes[1] in ("4", "5") and codes[0] == "F":
                bapo = "0"
            bapo += str(int(codes[1]) % 2) + codes[2:8]

            if codes[0] == "F":
                codetype = "F2F4"
                chksum = codes[9:11]
                xor = codes[11:15]
            elif codes[:2] in ("06", "07", "16", "17"):
                codetype = "0616"
            elif codes[:2] in ("04", "05", "14", "15"):
                codetype = "0414"

        if codetype == "0616":
            length = int(codes[9:17], 16)
            newindex = (length + 3) & -4
            if newindex % 8 == 0:
                return (codes[18:], bapo, xor, chksum, codetype)
            else:
                return (codes[18:-9], bapo, xor, chksum, codetype)

        elif codetype == "0414":
            fcodes = ""
            for i, line in enumerate(codes.split("\n")):
                fcodes += line[9:]
                if i % 2 == 0:
                    fcodes += " "
                else:
                    fcodes += "\n"
            return (fcodes.strip(), bapo, xor, chksum, codetype)

        if codes[-17:-9] == "60000000" or (codes[-17:] == "4E800020 00000000" and codetype == "C0" and cFooter):
            return (codes[18:-17], bapo, xor, chksum, codetype)
        else:
            return (codes[18:-9], bapo, xor, chksum, codetype)

    
    def disassemble(self, path: str):
        code = str()
        with open(path, "r") as f:
            code = f.read()
        return self.deconstruct_code(code)

    def run(self, path: str, script_path: str, type: str = "gecko"):
        if type == "gecko":
            out = self.disassemble(path)
            self.write_python(out, script_path)
